#!/usr/bin/python

from std_srvs.srv import Empty, EmptyResponse, Trigger
from std_msgs.msg import Int8
from std_msgs.msg import String
from villa_task import tts
import rospy


# speech = tts.TextToSpeech()

def speech_cb(msg):
    rospy.loginfo("Waiting for speech msgs...")
    Sentence = "Hello" +msg.data
    speech = tts.TextToSpeech()
    speech.say(Sentence, wait=True)
    # rospy.loginfo("Felt wrist tap.")
    return 

def speech_server():
    rospy.init_node('speech_node')
    speech = tts.TextToSpeech()
    speech.say("Hello. What can I do for you today?", wait=True)
    rospy.Subscriber("/face_detected_name",String,speech_cb)
    rospy.spin()

if __name__ == '__main__':
    speech_server()    
